import React, { ReactNode } from 'react'
import Head from 'next/head'
import Navbar from '../navigation/Navbar'
import Footer from '../footer/Footer'

type LandingLayoutProps = {
  children: ReactNode
}

const LandingLayout = (props: LandingLayoutProps) => {
  return (
    <div className="bg-gray-100">
      <Head>
        <title>Início</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>{props.children}</main>
      <Footer />
    </div>
  )
}

export default LandingLayout
