import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/navigation/Navbar'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Sporting Clube de Cabreiros</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <div className="relative bg-green-600">
          <div className="relative px-4 pt-8 mx-auto max-w-2xl text-center sm:px-6 sm:pt-12 lg:px-8 lg:max-w-7xl">
            <div className="w-full flex justify-center pb-8">
              <img src="/emblema.png" className="h-40 w-auto" />
            </div>
            <h1 className="text-4xl font-extrabold tracking-tight text-white sm:text-4xl">
              <span className="block lg:inline">Só está vencido aquele que admite ter sido derrotado</span>
            </h1>
            <p className="mt-4 text-xl text-green-100">Aqui vamos sempre por mais!</p>
          </div>
        </div> 
      </main>
    </div>
  )
}

export default Home
