import React, { ReactNode } from 'react'
import Navbar from '../navigation/Navbar'
import Footer from '../footer/Footer'
import Head from 'next/head'

type MainLayoutProps = {
  title?: string
  children: ReactNode
}

const Layout = (props: MainLayoutProps) => {
  return (
    <div className="bg-gray-100">
      <Head>
        <title>{props!.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <div className="min-h-screen">
          <div className="bg-green-600 text-white">
            <div className="flex items-center justify-center lg:justify-start pt-8 px-4 pb-8 mx-auto max-w-2xl sm:px-6 sm:pt-12 lg:px-8 lg:max-w-7xl ">
              <p className="text-2xl md:text-3xl">{props!.title}</p>
            </div>
          </div>
          {props.children}
        </div>
      </main>

      <Footer />
    </div>
  )
}

export default Layout
